version: '3.9'

networks:
  dev_network:

services:
  db:
    image: postgres:14.3-alpine3.15
    # чтобы не конфликтовать с постгресом, установленным на компе будем ипользовать 5431
    ports:
      - "5431:5432"
    # будем пробрасывать данные из переменных окружения
    # если их нет, до docker-compose умеет считывать их из .env файла!!
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}